apiVersion: v1
kind: Service
metadata:
  name: react-service-1320
spec:
  selector:
    app: react-1320
    version: "1.32.0"
  ports:
    - protocol: TCP
      targetport: 80
      port: 8082
  type: LoadBalancer