name: Version update pipeline
on:
  pull_request:
    types: [closed]
    branches:
    - release
env:
  NAME_VERSION_FILE: version
jobs:
  validate_branch:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: 
          echo "name step1"
          echo "name step1 - second command"
      - name: step2
        run: echo "name step2"
